version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
        name: Install dependencies
        command: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - persist_to_workspace:
        root: /home/circleci/project
        paths:
        - node_modules/*
        - dist/*
  lint:
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - attach_workspace:
        at: /home/circleci/project
    - run:
        name: Code linting
        command: npm run lint
  test:
    docker:
    - image: circleci/node:10.14.1
    steps:
    - checkout
    - attach_workspace:
        at: /home/circleci/project
    - run:
        name: Unit tests
        command: npm run test
  android:
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
    - checkout
    - attach_workspace:
        at: /home/circleci/project
    - run:
        name: create directory for index bundle 
        command: mkdir android/app/src/main/assets
    - run:
        name: accept License 
        command: yes | sdkmanager --licenses || exit 0
    - run:
        name: Android clean 
        command: npm run android-clean
    - run:
        name: Android bundle 
        command: npm run android-bundle
    - run:
        name: Android debug build
        command: npm run build-android-debug
    - store_artifacts:
        path: android/app/src/main/assets
    - store_artifacts:
        path: android/app/build/outputs/apk/debug
release:
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
    - checkout
    - attach_workspace:
        at: /home/circleci/project
    - run:
        name: create directory for index bundle 
        command: mkdir android/app/src/main/assets
    - run:
        name: accept License 
        command: yes | sdkmanager --licenses || exit 0
    - run:
        name: Android clean 
        command: npm run android-clean
    - run:
        name: Android bundle 
        command: npm run android-bundle
    - run:
        name: export release keystore 
        command: echo $RELEASE_KEYSTORE_BASE64 | base64 -d > android/app/boilerplate.keystore
    - run:
        name: export env to gradle properties 
        command: - source android/environmentSetup.sh && copyEnvVarsToGradleProperties
    - run:
        name: Android release build
        command: npm run build-android-release
    - store_artifacts:
        path: android/app/src/main/assets
    - store_artifacts:
        path: android/app/build/outputs/apk/
workflows:
  version: 2
  build_test_lint:
    jobs:
    - build
    - lint:
        requires:
        - build
    - test:
        requires:
        - build
    - android:
        requires:
        - build
    - release:
        requires:
        - build