name: 'Deploy Android App to Production'
description: 'Build and deploy the Android app to Production using Fastlane'
inputs:
  GPLAY_SERVICE_ACCOUNT_KEY_JSON:
    required: true
    description: 'Service Account Key JSON file for Google Play Store'
  KEYSTORE_FILE:
    required: true
    description: 'Keystore file for signing the Android app'
  KEYSTORE_PASSWORD:
    required: true
    description: 'Password for the keystore file'
  KEY_ALIAS:
    required: true
    description: 'Key alias for the keystore file'
  KEY_PASSWORD:
    required: true
    description: 'Password for the key alias'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: Set up NODE
      uses: actions/setup-node@v3
      with:
        node-version: 22.13.1

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-caches-

    - name: Install node modules
      run: yarn install
      shell: bash
      env:
        CI: true

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3"
        bundler-cache: true

    - name: Install Fastlane and dependencies
      shell: bash
      run: |
        gem install bundler
        cd android
        bundle install
      env:
        CI: true

    - name: Add @react-native-community manually
      shell: bash
      run: yarn add @react-native-community/cli-platform-android@11.3.3
      env:
        CI: true

    - name: Decode Service Account Key JSON File
      uses: timheuer/base64-to-file@v1
      id: service_account_json_file
      with:
        fileName: "serviceAccount.json"
        encodedString: ${{ inputs.GPLAY_SERVICE_ACCOUNT_KEY_JSON }}

    - name: Decode Keystore File
      uses: timheuer/base64-to-file@v1
      id: android_keystore
      with:
        fileName: "android_keystore.keystore"
        encodedString: ${{ inputs.KEYSTORE_FILE }}

    - name: Build and deploy android App via fastlane
      shell: bash
      run: bundle exec fastlane deploy_android_production
      working-directory: android
      env:
        KEYSTORE_FILE: ${{ steps.android_keystore.outputs.filePath }}
        KEYSTORE_PASSWORD: ${{ inputs.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ inputs.KEY_ALIAS }}
        KEY_PASSWORD: ${{ inputs.KEY_PASSWORD }}
        ANDROID_JSON_KEY_FILE: ${{ steps.service_account_json_file.outputs.filePath }}
