name: Version Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: pip install packaging

    - name: Run version comparison script
      run: python3 .github/scripts/version_check.py